#!/usr/bin/env node

/**
 * Generate version.ts file with version from package.json
 * This runs before TypeScript compilation
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Read version from package.json
const packageJson = JSON.parse(
  readFileSync(join(rootDir, 'package.json'), 'utf-8')
);
const version = packageJson.version;

// Generate version.ts
const versionFileContent = `/**
 * Auto-generated version file
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-version.js
 * Run 'pnpm build' to regenerate
 */

export const VERSION = '${version}';
`;

const versionFilePath = join(rootDir, 'src', 'version.ts');
writeFileSync(versionFilePath, versionFileContent);

console.log(`Generated src/version.ts with version ${version}`);
